version: "1.0"

name: React Frontend Docker Build

environment:
  NODE_ENV: production
  IMAGE_NAME: react-frontend
  IMAGE_TAG: latest

stages:
  - name: Build and tag Docker image
    steps:
      - name: Build Docker Image
        image: docker:24
        commands:
          - docker build -t $IMAGE_NAME:$IMAGE_TAG .
          - echo "Docker image build completed"
